# Generated by Django 5.2.8 on 2025-11-24 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text="Age de l'utilisateur", null=True)),
                ('niveau_cuisine', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='DEBUTANT', help_text='Niveau de compétence en cuisine', max_length=15)),
                ('ville', models.CharField(blank=True, help_text='Ville de résidence', max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo de profil utilisateur', null=True, upload_to='profils/')),
                ('bio', models.TextField(blank=True, help_text="Description courte de l'utilisateur", max_length=500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('region_origine', models.ForeignKey(blank=True, help_text="Région d'origine culinaire", null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
    ]
