# Generated by Django 5.2.8 on 2025-11-24 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categories_preferees', models.ManyToManyField(blank=True, help_text='Types de plats préférés (ex: Plats Principaux, Desserts)', to='recettes.categorie')),
                ('ingredients_evites', models.ManyToManyField(blank=True, help_text='Ingrédients à éviter (allergies, restrictions alimentaires)', to='recettes.ingredient')),
                ('regions_preferees', models.ManyToManyField(blank=True, help_text='Régions culinaires préférées (ex: Fès, Marrakech)', to='recettes.region')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Préférences Utilisateurs',
            },
        ),
    ]
