# Generated by Django 5.2.8 on 2025-11-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Régions',
            },
        ),
        migrations.CreateModel(
            name='QuantiteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(help_text='Ex: 200g, 1 cuillère à café', max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient')),
            ],
            options={
                'verbose_name_plural': "Quantités d'Ingrédients",
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(default='Étapes de préparation détaillées.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recettes_images/')),
                ('temps_preparation', models.IntegerField(help_text='En minutes')),
                ('temps_cuisson', models.IntegerField(help_text='En minutes')),
                ('niveau', models.CharField(choices=[('FACILE', 'Facile'), ('MOYEN', 'Moyen'), ('DIFFICILE', 'Difficile')], default='SIMLE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.categorie')),
                ('ingredients', models.ManyToManyField(through='recettes.QuantiteIngredient', to='recettes.ingredient')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recettes.region')),
            ],
            options={
                'verbose_name_plural': 'Recettes',
            },
        ),
        migrations.AddField(
            model_name='quantiteingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette'),
        ),
        migrations.AlterUniqueTogether(
            name='quantiteingredient',
            unique_together={('recette', 'ingredient')},
        ),
    ]
